version: '3.7'

services:
    api:
        # Purpose: application's local environment
        container_name: api
        build:
            context: ./env
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - ./env/go:/go/pkg/mod/cache
        ports:
            - 8080:8080
        depends_on:
            - db
        working_dir: /app
        env_file: ./env/.env
        networks:
            - payments
    db:
        # Purpose: application's database.
        container_name: db
        restart: always
        build:
            context: ./env
            dockerfile: Dockerfile.db.dev
        volumes:
            - ./env/db/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file: ./env/.env
        networks:
            - payments

networks:
    # Purpose: communication between application and database.
    payments:
        driver: bridge
